In [15]:
from transformers import GPT2LMHeadModel, AutoConfig, GPT2Model
from mymodelnew import MyModel
myconfig = AutoConfig.from_pretrained('gpt2')
mymodel = MyModel(myconfig)
#mymodel.save_pretrained('./tied-weights')



In [50]:
for name, param, in loadedmodel.decoder.lm_head.named_parameters():
    print(param)

Parameter containing:
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], requires_grad=True)


In [49]:
loadedmodel = MyModel.from_pretrained('./tied-weights')

Some weights of MyModel were not initialized from the model checkpoint at ./tied-weights and are newly initialized: ['decoder.lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [6]:
import torch
import numpy as np
a = torch.tensor([[1,2,3], [4,5,6]])
a[torch.arange(1)]

tensor([[1, 2, 3]])

In [ ]:
from transformers import GPT2LMHeadModel
mymodel = MyModel.from_pretrained('./backmodel3_weights_2024-07-26--21:40:09alaki')
mymodel

In [30]:
loadedmodel.decoder.lm_head

Linear(in_features=768, out_features=50257, bias=False)

In [31]:
for name, param in loadedmodel.decoder.lm_head.named_parameters():
    print('parameter name ', name)
    print('parameter value ', param)



parameter name  weight
parameter value  Parameter containing:
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], requires_grad=True)


In [55]:
mymodel.wte

AttributeError: 'GPT2Model' object has no attribute 'decoder'